# Generated by Django 5.2.5 on 2025-08-18 04:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_type', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS'), ('api', 'API')], default='api', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['id', 'client_type'], name='calculator__id_be02cb_idx')],
                'unique_together': {('id', 'client_type')},
            },
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expression', models.TextField()),
                ('result', models.FloatField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='calculator.client')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'created_at'], name='calculator__client__002b0e_idx'), models.Index(fields=['created_at'], name='calculator__created_0c5e9d_idx')],
            },
        ),
    ]
